<a href="https://colab.research.google.com/github/srinivasan-06/Python_for_DataScience-/blob/main/CourseNumpyHandson2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

**Create np array of zeroes of size (2, 3) run the following code**

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

 **Flatten 2D np Array to 1d np array.**

In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr.ravel()


In [ ]:
arr

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8]])

**create an 1D np array to 2D array**

In [ ]:
arr1 = np.array([1,2,3,4,5,6,7,8])
arr1.reshape((2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

**create an array and sort**

In [ ]:
arr2 = np.array([8,7,5,4,2,3,1])
np.sort(arr2)

array([1, 2, 3, 4, 5, 7, 8])

In [ ]:
arr2[2:]

array([5, 4, 2, 3, 1])