<a href="https://colab.research.google.com/github/srinivasan-06/Python_for_DataScience-/blob/main/Intellipaat_Numpy_Pandas_2025_10_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## <mark> Numpy

In [ ]:
import numpy as np

**Array Manipulations**

In [ ]:
# summation
4 + 4

8

In [ ]:
# concatenation
'four' + 'four'

'fourfour'

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [ ]:
#  concatenate both arrays
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# horizonrtal stacking
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
b = np.arange(10,19).reshape(3,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
# horizontal stack
np.hstack((a,b))

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [ ]:
# vertical stack
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
np.column_stack((a,b))

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

**Splitting the array**

In [ ]:
a = np.arange(0,16,1).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a.shape

(4, 4)

In [ ]:
# the split entity (row/column) must be even number

In [ ]:
# horizontal split
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
# vertical split
np.vsplit(a,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

-----------

In [ ]:
import time

In [ ]:
a = [1,2,3]
b = [4,5,6]

In [ ]:
#  python loop
for i in range(len(a)):
  print(a[i], '+', b[i], ' = ', a[i]+b[i])

1 + 4  =  5
2 + 5  =  7
3 + 6  =  9


In [ ]:
# list comprehension
[a[i]+b[i] for i in range(len(a))]

[5, 7, 9]

In [ ]:
# using python
def using_list(n):
  # start time
  start_time = time.time()

  list_1 = range(n)
  list_2 = range(n)

  # element wise addition using python
  result = [list_1[i] + list_2[i]  for i in range(len(list_1))]

  # end time
  end_time = time.time()

  # duration
  time_diff = end_time - start_time

  return time_diff

In [ ]:
# using numpy
def using_array(n):
  # start time
  start_time = time.time()

  array_1 = np.arange(n)
  array_2 = np.arange(n)

  # element wise addition using numpy
  result = array_1 + array_2

  # end time
  end_time = time.time()

  # duration
  time_diff = end_time - start_time

  return time_diff

In [ ]:
using_list(1000000)

0.21904253959655762

In [ ]:
using_array(1000000)

0.016629457473754883

In [ ]:
print(f'Numpy is {round(0.21904253959655762/0.016629457473754883, 0)} times faster than python')

Numpy is 13.0 times faster than python


In [ ]:
using_list(100000000)

24.215423822402954

In [ ]:
using_array(100000000)

1.5421640872955322

In [ ]:
print(f'Numpy is {round(24.215423822402954/1.5421640872955322, 0)} times faster than python')

Numpy is 16.0 times faster than python


-------------------------

## <mark> Pandas

+ Python Data Analysis library
+ **Pan**nel **Da**ta

In [ ]:
import pandas as pd

Syntax:
+ CSV file: `pd.read_csv('path_of_the_file.extension', delimiter=',')`
+ Excel file: `pd.read_excel('path_of_the_file.extension', sheet_name='name_of_the_sheet')`
  + dependency to read excel data --> install openpyxl library --> `pip install openpyxl`

|id|name|description|
|--|----|-----------|
|102|laptop|Apple Mac16|
|107|mobile|Vivo g32|
|134|shirt|plad with blue stipes, yellow lines and red finish|


+ id,name,description
+ 102,laptop,Apple Mac16
+ 107,mobile,Vivo g32
+ 134,shirt,plad with blue stipes, yellow lines and red finish

**delimiter=';'**

+ id;name;description
+ 102;laptop;Apple Mac16
+ 107;mobile;Vivo g32
+ 134;shirt;plad with blue stipes, yellow lines and red finish

Uncomment the below code, if executed in your local laptop

In [ ]:
# file_path = 'D:\\workspace\\notebooks\\datasets\\mtcars2.csv'
# pd.read_csv(file_path, delimiter=',')

uncomment the below code, if you are executing in colab

In [ ]:
cars_df = pd.read_csv('mtcars2.csv', delimiter=',')

In [ ]:
cars_df

S.No           Unnamed: 1   mpg  cyl   disp   hp  drat     wt   qsec  vs  \
0      1            Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   
1      2        Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   
2      3           Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   
3      4       Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   
4      5    Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   
5      6              Valiant  18.1    6  225.0  105  2.76  3.460    NaN   1   
6      7           Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   
7      8            Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   
8      9             Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   
9     10             Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   
10    11            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   
11    12           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   
12    13           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   
13    14          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   
14    15   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   
15    16  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   
16    17    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   
17    18             Fiat 128  32.4    4   78.7   66  4.08  2.200    NaN   1   
18    19          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   
19    20       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   
20    21        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   
21    22     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   
22    23          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   
23    24           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   
24    25     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   
25    26            Fiat X1-9  27.3    4   79.0   66  4.08  1.935    NaN   1   
26    27        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   
27    28         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   
28    29       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   
29    30         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   
30    31        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   
31    32           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   

    am  gear  carb  
0    1     4     4  
1    1     4     4  
2    1     4     1  
3    0     3     1  
4    0     3     2  
5    0     3     1  
6    0     3     4  
7    0     4     2  
8    0     4     2  
9    0     4     4  
10   0     4     4  
11   0     3     3  
12   0     3     3  
13   0     3     3  
14   0     3     4  
15   0     3     4  
16   0     3     4  
17   1     4     1  
18   1     4     2  
19   1     4     1  
20   0     3     1  
21   0     3     2  
22   0     3     2  
23   0     3     4  
24   0     3     2  
25   1     4     1  
26   1     5     2  
27   1     5     2  
28   1     5     4  
29   1     5     6  
30   1     5     8  
31   1     4     2

| **Variable** | **Description**                                                                                          | **Type / Unit**            |
| ------------ | -------------------------------------------------------------------------------------------------------- | -------------------------- |
| `S.No`       | Serial number (index of each car)                                                                        | Integer                    |
| `Unnamed: 1` | Likely the **car model name** (the column sometimes appears unnamed when the dataset is exported from R) | Text                       |
| `mpg`        | **Miles per gallon** – fuel efficiency (higher = better)                                                 | Numeric (miles per gallon) |
| `cyl`        | **Number of cylinders** in the engine                                                                    | Integer                    |
| `disp`       | **Displacement** – total volume of the engine cylinders                                                  | Numeric (cubic inches)     |
| `hp`         | **Gross horsepower** – engine power output                                                               | Numeric                    |
| `drat`       | **Rear axle ratio** – gear ratio of the differential                                                     | Numeric                    |
| `wt`         | **Weight** of the car                                                                                    | Numeric (in 1,000 lbs)     |
| `qsec`       | **1/4 mile time** – time it takes to travel a quarter mile                                               | Numeric (seconds)          |
| `vs`         | **Engine shape**: 0 = V-shaped, 1 = straight (inline)                                                    | Binary (0 or 1)            |
| `am`         | **Transmission type**: 0 = automatic, 1 = manual                                                         | Binary (0 or 1)            |
| `gear`       | **Number of forward gears**                                                                              | Integer                    |
| `carb`       | **Number of carburetors**                                                                                | Integer                    |


**Analyzing the dataset**

In [ ]:
cars_df.shape

(32, 13)

In [ ]:
print(f'Rows: {cars_df.shape[0]}')
print(f'Cols: {cars_df.shape[1]}')

Rows: 32
Cols: 13


Display top rows

In [ ]:
# default it shows top 5 rows
cars_df.head()

S.No         Unnamed: 1   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0     1          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1     2      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2     3         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3     4     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     5  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   

   gear  carb  
0     4     4  
1     4     4  
2     4     1  
3     3     1  
4     3     2

In [ ]:
# display top 8 rows
cars_df.head(8)

S.No         Unnamed: 1   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0     1          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1     2      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2     3         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3     4     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     5  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5     6            Valiant  18.1    6  225.0  105  2.76  3.460    NaN   1   0   
6     7         Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7     8          Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   

   gear  carb  
0     4     4  
1     4     4  
2     4     1  
3     3     1  
4     3     2  
5     3     1  
6     3     4  
7     4     2

Access bottom rows

In [ ]:
# bottom 4 rows
cars_df.tail(4)

S.No      Unnamed: 1   mpg  cyl   disp   hp  drat    wt  qsec  vs  am  \
28    29  Ford Pantera L  15.8    8  351.0  264  4.22  3.17  14.5   0   1   
29    30    Ferrari Dino  19.7    6  145.0  175  3.62  2.77  15.5   0   1   
30    31   Maserati Bora  15.0    8  301.0  335  3.54  3.57  14.6   0   1   
31    32      Volvo 142E  21.4    4  121.0  109  4.11  2.78  18.6   1   1   

    gear  carb  
28     5     4  
29     5     6  
30     5     8  
31     4     2

Access random rows

In [ ]:
cars_df.sample()

S.No  Unnamed: 1   mpg  cyl   disp   hp  drat    wt  qsec  vs  am  gear  \
12    13  Merc 450SL  17.3    8  275.8  180  3.07  3.73  17.6   0   0     3   

    carb  
12     3

In [ ]:
# get 3 samples
cars_df.sample(3)

S.No     Unnamed: 1   mpg  cyl   disp  hp  drat     wt  qsec  vs  am  \
25    26      Fiat X1-9  27.3    4   79.0  66  4.08  1.935   NaN   1   1   
26    27  Porsche 914-2  26.0    4  120.3  91  4.43  2.140  16.7   0   1   
17    18       Fiat 128  32.4    4   78.7  66  4.08  2.200   NaN   1   1   

    gear  carb  
25     4     1  
26     5     2  
17     4     1

In [ ]:
cars_df.columns

Index(['S.No', 'Unnamed: 1', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec',
       'vs', 'am', 'gear', 'carb'],
      dtype='object')

In [ ]:
cars_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   S.No        32 non-null     int64  
 1   Unnamed: 1  32 non-null     object 
 2   mpg         32 non-null     float64
 3   cyl         32 non-null     int64  
 4   disp        32 non-null     float64
 5   hp          32 non-null     int64  
 6   drat        32 non-null     float64
 7   wt          32 non-null     float64
 8   qsec        29 non-null     float64
 9   vs          32 non-null     int64  
 10  am          32 non-null     int64  
 11  gear        32 non-null     int64  
 12  carb        32 non-null     int64  
dtypes: float64(5), int64(7), object(1)
memory usage: 3.4+ KB


In [ ]:
cars_df.describe()

S.No        mpg        cyl        disp          hp       drat  \
count  32.000000  32.000000  32.000000   32.000000   32.000000  32.000000   
mean   16.500000  20.090625   6.187500  230.721875  146.687500   3.596563   
std     9.380832   6.026948   1.785922  123.938694   68.562868   0.534679   
min     1.000000  10.400000   4.000000   71.100000   52.000000   2.760000   
25%     8.750000  15.425000   4.000000  120.825000   96.500000   3.080000   
50%    16.500000  19.200000   6.000000  196.300000  123.000000   3.695000   
75%    24.250000  22.800000   8.000000  326.000000  180.000000   3.920000   
max    32.000000  33.900000   8.000000  472.000000  335.000000   4.930000   

              wt       qsec         vs         am       gear     carb  
count  32.000000  29.000000  32.000000  32.000000  32.000000  32.0000  
mean    3.217250  17.674828   0.437500   0.406250   3.687500   2.8125  
std     0.978457   1.780394   0.504016   0.498991   0.737804   1.6152  
min     1.513000  14.500000   0.000000   0.000000   3.000000   1.0000  
25%     2.581250  16.870000   0.000000   0.000000   3.000000   2.0000  
50%     3.325000  17.420000   0.000000   0.000000   4.000000   2.0000  
75%     3.610000  18.600000   1.000000   1.000000   4.000000   4.0000  
max     5.424000  22.900000   1.000000   1.000000   5.000000   8.0000

**Access the dataset**

In [ ]:
cars_df.columns

Index(['S.No', 'Unnamed: 1', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec',
       'vs', 'am', 'gear', 'carb'],
      dtype='object')

**Approach 1:** Dot method

In [ ]:
cars_df.mpg

0     21.0
1     21.0
2     22.8
3     21.4
4     18.7
5     18.1
6     14.3
7     24.4
8     22.8
9     19.2
10    17.8
11    16.4
12    17.3
13    15.2
14    10.4
15    10.4
16    14.7
17    32.4
18    30.4
19    33.9
20    21.5
21    15.5
22    15.2
23    13.3
24    19.2
25    27.3
26    26.0
27    30.4
28    15.8
29    19.7
30    15.0
31    21.4
Name: mpg, dtype: float64

In [ ]:
# chain linkage the commands
cars_df.hp.head()

0    110
1    110
2     93
3    110
4    175
Name: hp, dtype: int64

In [ ]:
cars_df.hp.head().mean()

np.float64(119.6)

In [ ]:
cars_df.hp.tail().mean()

np.float64(199.2)

In [ ]:
cars_df.hp.describe()

count     32.000000
mean     146.687500
std       68.562868
min       52.000000
25%       96.500000
50%      123.000000
75%      180.000000
max      335.000000
Name: hp, dtype: float64

In [ ]:
cars_df.columns

Index(['S.No', 'Unnamed: 1', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec',
       'vs', 'am', 'gear', 'carb'],
      dtype='object')

In [ ]:
cars_df.S.No

AttributeError: 'DataFrame' object has no attribute 'S'

**Approach 2:** filter by Square bracket

In [ ]:
cars_df['S.No'].head()

0    1
1    2
2    3
3    4
4    5
Name: S.No, dtype: int64

In [ ]:
cars_df['Unnamed: 1'].tail()

27      Lotus Europa
28    Ford Pantera L
29      Ferrari Dino
30     Maserati Bora
31        Volvo 142E
Name: Unnamed: 1, dtype: object

**Data Manipulation**

Backup of the original data

In [ ]:
cars_bkp_df = cars_df.copy()

It is a shallow copy

In [ ]:
a = [1,2,3,4]
a

[1, 2, 3, 4]

In [ ]:
b = a
b

[1, 2, 3, 4]

In [ ]:
a.append(5)
a

[1, 2, 3, 4, 5]

In [ ]:
b

[1, 2, 3, 4, 5]

Create independent deep copy

In [ ]:
cars_bkp_df = cars_df.copy(deep=True)

+ this creates an actual copy independent of original data
+ this is a temporary backup, it is lost after restarting the kernal

In [ ]:
cars_df.head()

S.No         Unnamed: 1   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0     1          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1     2      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2     3         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3     4     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     5  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   

   gear  carb  
0     4     4  
1     4     4  
2     4     1  
3     3     1  
4     3     2

In [ ]:
# permanant way of backup
cars_df.to_csv('mtcars2_bkp.csv', index=False)

**Data Wrangling (cleaning)**

1. check for null values

In [ ]:
cars_df.isna()

S.No  Unnamed: 1    mpg    cyl   disp     hp   drat     wt   qsec     vs  \
0   False       False  False  False  False  False  False  False  False  False   
1   False       False  False  False  False  False  False  False  False  False   
2   False       False  False  False  False  False  False  False  False  False   
3   False       False  False  False  False  False  False  False  False  False   
4   False       False  False  False  False  False  False  False  False  False   
5   False       False  False  False  False  False  False  False   True  False   
6   False       False  False  False  False  False  False  False  False  False   
7   False       False  False  False  False  False  False  False  False  False   
8   False       False  False  False  False  False  False  False  False  False   
9   False       False  False  False  False  False  False  False  False  False   
10  False       False  False  False  False  False  False  False  False  False   
11  False       False  False  False  False  False  False  False  False  False   
12  False       False  False  False  False  False  False  False  False  False   
13  False       False  False  False  False  False  False  False  False  False   
14  False       False  False  False  False  False  False  False  False  False   
15  False       False  False  False  False  False  False  False  False  False   
16  False       False  False  False  False  False  False  False  False  False   
17  False       False  False  False  False  False  False  False   True  False   
18  False       False  False  False  False  False  False  False  False  False   
19  False       False  False  False  False  False  False  False  False  False   
20  False       False  False  False  False  False  False  False  False  False   
21  False       False  False  False  False  False  False  False  False  False   
22  False       False  False  False  False  False  False  False  False  False   
23  False       False  False  False  False  False  False  False  False  False   
24  False       False  False  False  False  False  False  False  False  False   
25  False       False  False  False  False  False  False  False   True  False   
26  False       False  False  False  False  False  False  False  False  False   
27  False       False  False  False  False  False  False  False  False  False   
28  False       False  False  False  False  False  False  False  False  False   
29  False       False  False  False  False  False  False  False  False  False   
30  False       False  False  False  False  False  False  False  False  False   
31  False       False  False  False  False  False  False  False  False  False   

       am   gear   carb  
0   False  False  False  
1   False  False  False  
2   False  False  False  
3   False  False  False  
4   False  False  False  
5   False  False  False  
6   False  False  False  
7   False  False  False  
8   False  False  False  
9   False  False  False  
10  False  False  False  
11  False  False  False  
12  False  False  False  
13  False  False  False  
14  False  False  False  
15  False  False  False  
16  False  False  False  
17  False  False  False  
18  False  False  False  
19  False  False  False  
20  False  False  False  
21  False  False  False  
22  False  False  False  
23  False  False  False  
24  False  False  False  
25  False  False  False  
26  False  False  False  
27  False  False  False  
28  False  False  False  
29  False  False  False  
30  False  False  False  
31  False  False  False

In [ ]:
# column wise null count
cars_df.isna().sum()

S.No          0
Unnamed: 1    0
mpg           0
cyl           0
disp          0
hp            0
drat          0
wt            0
qsec          3
vs            0
am            0
gear          0
carb          0
dtype: int64

In [ ]:
#  entire dataset null count
cars_df.isna().sum().sum()

np.int64(3)

Should we drop the null values or not?

In [ ]:
null_count = cars_df.isna().sum().sum()
null_count

np.int64(3)

In [ ]:
data_loss_pct = (null_count / cars_df.shape[0]) * 100
print(f"Data loss is {data_loss_pct}%")

Data loss is 9.375%


If the data loss is more than 5%, do not drop the data

Replace this null values in `qsec` col , with its own average value

In [ ]:
qsec_avg = cars_df.qsec.mean()
qsec_avg

np.float64(17.6748275862069)

In [ ]:
# fill null values in qsec col
cars_df['qsec'].fillna(qsec_avg)

0     16.460000
1     17.020000
2     18.610000
3     19.440000
4     17.020000
5     17.674828
6     15.840000
7     20.000000
8     22.900000
9     18.300000
10    18.900000
11    17.400000
12    17.600000
13    18.000000
14    17.980000
15    17.820000
16    17.420000
17    17.674828
18    18.520000
19    19.900000
20    20.010000
21    16.870000
22    17.300000
23    15.410000
24    17.050000
25    17.674828
26    16.700000
27    16.900000
28    14.500000
29    15.500000
30    14.600000
31    18.600000
Name: qsec, dtype: float64

In [ ]:
cars_df.isna().sum()

S.No          0
Unnamed: 1    0
mpg           0
cyl           0
disp          0
hp            0
drat          0
wt            0
qsec          3
vs            0
am            0
gear          0
carb          0
dtype: int64

**Making the changes permanant**

+ if output is displayed, then it is a temporaray change
+ if output is not displayed, then it is a permanant change

**Approach 1:** Update itself

In [ ]:
a = 1
a

1

In [ ]:
a + 5

6

In [ ]:
a

1

In [ ]:
# update itslef
a = a + 5
a

6

In [ ]:
# permanant change - update qsec col
cars_df['qsec'] = cars_df['qsec'].fillna(qsec_avg)

In [ ]:
cars_df.isna().sum()

S.No          0
Unnamed: 1    0
mpg           0
cyl           0
disp          0
hp            0
drat          0
wt            0
qsec          0
vs            0
am            0
gear          0
carb          0
dtype: int64

**Approach 2:** `inplace` parameter

In [ ]:
cars_df['qsec'].fillna(qsec_avg, inplace=True)

/tmp/ipython-input-189616658.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cars_df['qsec'].fillna(qsec_avg, inplace=True)


In [ ]:
col_list = ['mpg', 'hp', 'qsec']
cars_df[col_list].head()

mpg   hp   qsec
0  21.0  110  16.46
1  21.0  110  17.02
2  22.8   93  18.61
3  21.4  110  19.44
4  18.7  175  17.02

In [ ]:
cars_df[['mpg', 'hp', 'qsec']].head()

mpg   hp   qsec
0  21.0  110  16.46
1  21.0  110  17.02
2  22.8   93  18.61
3  21.4  110  19.44
4  18.7  175  17.02

In [ ]:
cars_df[['mpg', 'hp', 'qsec']].fillna(0)

mpg   hp       qsec
0   21.0  110  16.460000
1   21.0  110  17.020000
2   22.8   93  18.610000
3   21.4  110  19.440000
4   18.7  175  17.020000
5   18.1  105  17.674828
6   14.3  245  15.840000
7   24.4   62  20.000000
8   22.8   95  22.900000
9   19.2  123  18.300000
10  17.8  123  18.900000
11  16.4  180  17.400000
12  17.3  180  17.600000
13  15.2  180  18.000000
14  10.4  205  17.980000
15  10.4  215  17.820000
16  14.7  230  17.420000
17  32.4   66  17.674828
18  30.4   52  18.520000
19  33.9   65  19.900000
20  21.5   97  20.010000
21  15.5  150  16.870000
22  15.2  150  17.300000
23  13.3  245  15.410000
24  19.2  175  17.050000
25  27.3   66  17.674828
26  26.0   91  16.700000
27  30.4  113  16.900000
28  15.8  264  14.500000
29  19.7  175  15.500000
30  15.0  335  14.600000
31  21.4  109  18.600000

**Drop un-necessary data**

In [ ]:
cars_df.columns

Index(['S.No', 'Unnamed: 1', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec',
       'vs', 'am', 'gear', 'carb'],
      dtype='object')

In [ ]:
cars_df.head()

S.No         Unnamed: 1   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0     1          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1     2      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2     3         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3     4     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     5  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   

   gear  carb  
0     4     4  
1     4     4  
2     4     1  
3     3     1  
4     3     2

Drop S.No from the data

In [ ]:
cars_df.drop(columns=['S.No','mpg', 'hp'])

Unnamed: 1  cyl   disp  drat     wt       qsec  vs  am  gear  \
0             Mazda RX4    6  160.0  3.90  2.620  16.460000   0   1     4   
1         Mazda RX4 Wag    6  160.0  3.90  2.875  17.020000   0   1     4   
2            Datsun 710    4  108.0  3.85  2.320  18.610000   1   1     4   
3        Hornet 4 Drive    6  258.0  3.08  3.215  19.440000   1   0     3   
4     Hornet Sportabout    8  360.0  3.15  3.440  17.020000   0   0     3   
5               Valiant    6  225.0  2.76  3.460  17.674828   1   0     3   
6            Duster 360    8  360.0  3.21  3.570  15.840000   0   0     3   
7             Merc 240D    4  146.7  3.69  3.190  20.000000   1   0     4   
8              Merc 230    4  140.8  3.92  3.150  22.900000   1   0     4   
9              Merc 280    6  167.6  3.92  3.440  18.300000   1   0     4   
10            Merc 280C    6  167.6  3.92  3.440  18.900000   1   0     4   
11           Merc 450SE    8  275.8  3.07  4.070  17.400000   0   0     3   
12           Merc 450SL    8  275.8  3.07  3.730  17.600000   0   0     3   
13          Merc 450SLC    8  275.8  3.07  3.780  18.000000   0   0     3   
14   Cadillac Fleetwood    8  472.0  2.93  5.250  17.980000   0   0     3   
15  Lincoln Continental    8  460.0  3.00  5.424  17.820000   0   0     3   
16    Chrysler Imperial    8  440.0  3.23  5.345  17.420000   0   0     3   
17             Fiat 128    4   78.7  4.08  2.200  17.674828   1   1     4   
18          Honda Civic    4   75.7  4.93  1.615  18.520000   1   1     4   
19       Toyota Corolla    4   71.1  4.22  1.835  19.900000   1   1     4   
20        Toyota Corona    4  120.1  3.70  2.465  20.010000   1   0     3   
21     Dodge Challenger    8  318.0  2.76  3.520  16.870000   0   0     3   
22          AMC Javelin    8  304.0  3.15  3.435  17.300000   0   0     3   
23           Camaro Z28    8  350.0  3.73  3.840  15.410000   0   0     3   
24     Pontiac Firebird    8  400.0  3.08  3.845  17.050000   0   0     3   
25            Fiat X1-9    4   79.0  4.08  1.935  17.674828   1   1     4   
26        Porsche 914-2    4  120.3  4.43  2.140  16.700000   0   1     5   
27         Lotus Europa    4   95.1  3.77  1.513  16.900000   1   1     5   
28       Ford Pantera L    8  351.0  4.22  3.170  14.500000   0   1     5   
29         Ferrari Dino    6  145.0  3.62  2.770  15.500000   0   1     5   
30        Maserati Bora    8  301.0  3.54  3.570  14.600000   0   1     5   
31           Volvo 142E    4  121.0  4.11  2.780  18.600000   1   1     4   

    carb  
0      4  
1      4  
2      1  
3      1  
4      2  
5      1  
6      4  
7      2  
8      2  
9      4  
10     4  
11     3  
12     3  
13     3  
14     4  
15     4  
16     4  
17     1  
18     2  
19     1  
20     1  
21     2  
22     2  
23     4  
24     2  
25     1  
26     2  
27     2  
28     4  
29     6  
30     8  
31     2

In [ ]:
# cars_df = cars_df.drop(columns=['S.No'])
cars_df.drop(columns=['S.No'], inplace=True)

In [ ]:
cars_df.columns

Index(['Unnamed: 1', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs',
       'am', 'gear', 'carb'],
      dtype='object')

Drop the rows

In [ ]:
#  drop row 1,3,4,6
cars_df.drop([1,3,4,6]).head(10)

Unnamed: 1   mpg  cyl   disp   hp  drat    wt       qsec  vs  am  gear  \
0     Mazda RX4  21.0    6  160.0  110  3.90  2.62  16.460000   0   1     4   
2    Datsun 710  22.8    4  108.0   93  3.85  2.32  18.610000   1   1     4   
5       Valiant  18.1    6  225.0  105  2.76  3.46  17.674828   1   0     3   
7     Merc 240D  24.4    4  146.7   62  3.69  3.19  20.000000   1   0     4   
8      Merc 230  22.8    4  140.8   95  3.92  3.15  22.900000   1   0     4   
9      Merc 280  19.2    6  167.6  123  3.92  3.44  18.300000   1   0     4   
10    Merc 280C  17.8    6  167.6  123  3.92  3.44  18.900000   1   0     4   
11   Merc 450SE  16.4    8  275.8  180  3.07  4.07  17.400000   0   0     3   
12   Merc 450SL  17.3    8  275.8  180  3.07  3.73  17.600000   0   0     3   
13  Merc 450SLC  15.2    8  275.8  180  3.07  3.78  18.000000   0   0     3   

    carb  
0      4  
2      1  
5      1  
7      2  
8      2  
9      4  
10     4  
11     3  
12     3  
13     3

In [ ]:
#  drop row 1,3,4,6 and reset the index
cars_df.drop([1,3,4,6]).reset_index()

index           Unnamed: 1   mpg  cyl   disp   hp  drat     wt       qsec  \
0       0            Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.460000   
1       2           Datsun 710  22.8    4  108.0   93  3.85  2.320  18.610000   
2       5              Valiant  18.1    6  225.0  105  2.76  3.460  17.674828   
3       7            Merc 240D  24.4    4  146.7   62  3.69  3.190  20.000000   
4       8             Merc 230  22.8    4  140.8   95  3.92  3.150  22.900000   
5       9             Merc 280  19.2    6  167.6  123  3.92  3.440  18.300000   
6      10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.900000   
7      11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.400000   
8      12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.600000   
9      13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.000000   
10     14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.980000   
11     15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.820000   
12     16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.420000   
13     17             Fiat 128  32.4    4   78.7   66  4.08  2.200  17.674828   
14     18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.520000   
15     19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.900000   
16     20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.010000   
17     21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.870000   
18     22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.300000   
19     23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.410000   
20     24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.050000   
21     25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  17.674828   
22     26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.700000   
23     27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.900000   
24     28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.500000   
25     29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.500000   
26     30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.600000   
27     31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.600000   

    vs  am  gear  carb  
0    0   1     4     4  
1    1   1     4     1  
2    1   0     3     1  
3    1   0     4     2  
4    1   0     4     2  
5    1   0     4     4  
6    1   0     4     4  
7    0   0     3     3  
8    0   0     3     3  
9    0   0     3     3  
10   0   0     3     4  
11   0   0     3     4  
12   0   0     3     4  
13   1   1     4     1  
14   1   1     4     2  
15   1   1     4     1  
16   1   0     3     1  
17   0   0     3     2  
18   0   0     3     2  
19   0   0     3     4  
20   0   0     3     2  
21   1   1     4     1  
22   0   1     5     2  
23   1   1     5     2  
24   0   1     5     4  
25   0   1     5     6  
26   0   1     5     8  
27   1   1     4     2

In [ ]:
#  drop row 1,3,4,6 and reset the index and drop the old index
cars_df.drop([1,3,4,6]).reset_index(drop=True)

Unnamed: 1   mpg  cyl   disp   hp  drat     wt       qsec  vs  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.460000   0   
1            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.610000   1   
2               Valiant  18.1    6  225.0  105  2.76  3.460  17.674828   1   
3             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.000000   1   
4              Merc 230  22.8    4  140.8   95  3.92  3.150  22.900000   1   
5              Merc 280  19.2    6  167.6  123  3.92  3.440  18.300000   1   
6             Merc 280C  17.8    6  167.6  123  3.92  3.440  18.900000   1   
7            Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.400000   0   
8            Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.600000   0   
9           Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.000000   0   
10   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.980000   0   
11  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.820000   0   
12    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.420000   0   
13             Fiat 128  32.4    4   78.7   66  4.08  2.200  17.674828   1   
14          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.520000   1   
15       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.900000   1   
16        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.010000   1   
17     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.870000   0   
18          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.300000   0   
19           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.410000   0   
20     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.050000   0   
21            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  17.674828   1   
22        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.700000   0   
23         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.900000   1   
24       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.500000   0   
25         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.500000   0   
26        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.600000   0   
27           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.600000   1   

    am  gear  carb  
0    1     4     4  
1    1     4     1  
2    0     3     1  
3    0     4     2  
4    0     4     2  
5    0     4     4  
6    0     4     4  
7    0     3     3  
8    0     3     3  
9    0     3     3  
10   0     3     4  
11   0     3     4  
12   0     3     4  
13   1     4     1  
14   1     4     2  
15   1     4     1  
16   0     3     1  
17   0     3     2  
18   0     3     2  
19   0     3     4  
20   0     3     2  
21   1     4     1  
22   1     5     2  
23   1     5     2  
24   1     5     4  
25   1     5     6  
26   1     5     8  
27   1     4     2

**Renaming the columns**

In [ ]:
cars_df.columns

Index(['Unnamed: 1', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs',
       'am', 'gear', 'carb'],
      dtype='object')

In [ ]:
# rename 'Unnnamed: 1' to 'model' and 'wt' to 'weight'
cars_df.rename(columns={'Unnamed: 1':'model', 'wt':'weight'})

model   mpg  cyl   disp   hp  drat  weight       qsec  vs  \
0             Mazda RX4  21.0    6  160.0  110  3.90   2.620  16.460000   0   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90   2.875  17.020000   0   
2            Datsun 710  22.8    4  108.0   93  3.85   2.320  18.610000   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08   3.215  19.440000   1   
4     Hornet Sportabout  18.7    8  360.0  175  3.15   3.440  17.020000   0   
5               Valiant  18.1    6  225.0  105  2.76   3.460  17.674828   1   
6            Duster 360  14.3    8  360.0  245  3.21   3.570  15.840000   0   
7             Merc 240D  24.4    4  146.7   62  3.69   3.190  20.000000   1   
8              Merc 230  22.8    4  140.8   95  3.92   3.150  22.900000   1   
9              Merc 280  19.2    6  167.6  123  3.92   3.440  18.300000   1   
10            Merc 280C  17.8    6  167.6  123  3.92   3.440  18.900000   1   
11           Merc 450SE  16.4    8  275.8  180  3.07   4.070  17.400000   0   
12           Merc 450SL  17.3    8  275.8  180  3.07   3.730  17.600000   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07   3.780  18.000000   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93   5.250  17.980000   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00   5.424  17.820000   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23   5.345  17.420000   0   
17             Fiat 128  32.4    4   78.7   66  4.08   2.200  17.674828   1   
18          Honda Civic  30.4    4   75.7   52  4.93   1.615  18.520000   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22   1.835  19.900000   1   
20        Toyota Corona  21.5    4  120.1   97  3.70   2.465  20.010000   1   
21     Dodge Challenger  15.5    8  318.0  150  2.76   3.520  16.870000   0   
22          AMC Javelin  15.2    8  304.0  150  3.15   3.435  17.300000   0   
23           Camaro Z28  13.3    8  350.0  245  3.73   3.840  15.410000   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08   3.845  17.050000   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08   1.935  17.674828   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43   2.140  16.700000   0   
27         Lotus Europa  30.4    4   95.1  113  3.77   1.513  16.900000   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22   3.170  14.500000   0   
29         Ferrari Dino  19.7    6  145.0  175  3.62   2.770  15.500000   0   
30        Maserati Bora  15.0    8  301.0  335  3.54   3.570  14.600000   0   
31           Volvo 142E  21.4    4  121.0  109  4.11   2.780  18.600000   1   

    am  gear  carb  
0    1     4     4  
1    1     4     4  
2    1     4     1  
3    0     3     1  
4    0     3     2  
5    0     3     1  
6    0     3     4  
7    0     4     2  
8    0     4     2  
9    0     4     4  
10   0     4     4  
11   0     3     3  
12   0     3     3  
13   0     3     3  
14   0     3     4  
15   0     3     4  
16   0     3     4  
17   1     4     1  
18   1     4     2  
19   1     4     1  
20   0     3     1  
21   0     3     2  
22   0     3     2  
23   0     3     4  
24   0     3     2  
25   1     4     1  
26   1     5     2  
27   1     5     2  
28   1     5     4  
29   1     5     6  
30   1     5     8  
31   1     4     2

In [ ]:
# rename 'Unnnamed: 1' to 'model' and 'wt' to 'weight'
cars_df.rename(columns={'Unnamed: 1':'model', 'wt':'weight'}, inplace=True)

In [ ]:
cars_df.columns

Index(['model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'weight', 'qsec', 'vs',
       'am', 'gear', 'carb'],
      dtype='object')

---------