<a href="https://colab.research.google.com/github/srinivasan-06/Python_for_DataScience-/blob/main/Intellipaat_Numpy_2025_10_25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## <mark> Numpy
+ Num - Numerical
+ Py - Python

In [ ]:
# python list - support multiple datatypes
item_list = ['string', 5, 8.6, True]

+ datatype?
+ memory allocation

### Array
+ all elements are single datatype
+ result in continuous memory allocation

------

INstall the library

In [ ]:
!pip install numpy

Load the library

In [ ]:
import numpy as np

**Example:**

+ HD - 1080 pixels per inch
+ 55 inch screen
+ Total it contain 59,400 pixels/led's in TV
+ Each LED contain 3 colors (Red, Green, Blue)
+ 8 bit microcontroller - 2*8 = 256 values - (0-dark, 255-bright)
+ in total, full screen has 59,400 * 3 = 1,78,299 values broadcasted for 1 image
+ Image to video generations (fps) - 24 frames per second
+ information processed in 1 second = 42,76,800

**Create 1D Array**

In [ ]:
num_list = [3,5,7,8,3,5,7]

#  convert list into an array
num_array = np.array(num_list)
num_array

array([3, 5, 7, 8, 3, 5, 7])

In [ ]:
num_array.dtype

dtype('int64')

In [ ]:
# list with multiple datatypes
random_list = [1,4,8.9,2.3,5,7,1]

# convert it into array
random_array = np.array(random_list)
random_array

array([1. , 4. , 8.9, 2.3, 5. , 7. , 1. ])

In [ ]:
random_array.dtype

dtype('float64')

In [ ]:
# list with multiple datatypes
random_list = [1,4,8.9,2.3,5,7,'ten']

# convert it into array
random_array = np.array(random_list)
random_array

array(['1', '4', '8.9', '2.3', '5', '7', 'ten'], dtype='<U32')

**Inspect 1D Array**

In [ ]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
#  check the data structure
type(a)

numpy.ndarray

nd array - n dimensional array

In [ ]:
#  check the data type of the elements
a.dtype

dtype('int64')

In [ ]:
# check the dimensions
a.ndim

1

In [ ]:
a.shape

(4,)

In [ ]:
#  check no of elements
a.size

4

------------

**2D Array**

In [ ]:
elem_1 = [1,2,3,4]
elem_2 = [5,6,7,8]
elem_3 = [3,5,6,2]

list_of_lists = [ elem_1, elem_2, elem_3 ]

#  convert into 2D Array
array_2d = np.array(list_of_lists)
array_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [3, 5, 6, 2]])

In [ ]:
array_2d.ndim

2

In [ ]:
array_2d.shape

(3, 4)

In [ ]:
array_2d.size

12

+ Adding/increasing rows or columns, does not increase the no of dimensions

------------

**Deep dive on Dimensions**

1D Array

In [ ]:
student_list = [1,2,3,4]
class_array = np.array(student_list)
class_array

array([1, 2, 3, 4])

In [ ]:
class_array.shape

(4,)

2D Array

In [ ]:
class_1 = [1,2,3,4]   # ---> 1D Array
class_2 = [5,6,7,8]   # ---> 1D Array
class_3 = [1,2,3,4]   # ---> 1D Array

college_array = np.array([class_1, class_2, class_3])
college_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [ ]:
college_array.shape

(3, 4)

3D Array

In [ ]:
college_1 = [ [1,2,3,4,5],  [6,7,8,9,10] ]           # ---> 2D Array
college_2 = [ [11,24,63,12,65],  [64,23,16,75,23]]   # ---> 2D Array

university_array = np.array([college_1, college_2])
university_array

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 24, 63, 12, 65],
        [64, 23, 16, 75, 23]]])

In [ ]:
university_array.shape

(2, 2, 5)

4D Array

In [ ]:
university_1 = [ [[1,2,3,4], [5,6,7,8]] ,  [[1,2,3,4], [5,6,7,8]]  ]   # ---> 3D Array
university_2 = [ [[1,2,3,4], [5,6,7,8]] ,  [[1,2,3,4], [5,6,7,8]]  ]   # ---> 3D Array

zonal_array = np.array([university_1, university_2])
zonal_array

array([[[[1, 2, 3, 4],
         [5, 6, 7, 8]],

        [[1, 2, 3, 4],
         [5, 6, 7, 8]]],


       [[[1, 2, 3, 4],
         [5, 6, 7, 8]],

        [[1, 2, 3, 4],
         [5, 6, 7, 8]]]])

In [ ]:
zonal_array.shape

(2, 2, 2, 4)

---------

**Array Initialization**

`Using List`

In [ ]:
a = [1,2,45,7]
a = np.array(a)
a

array([ 1,  2, 45,  7])

`Using Full method`

In [ ]:
help(np.full)

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C', *, device=None, like=None)
    Return a new array of given shape and type, filled with `fill_value`.

    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar or array_like
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, None, means
         ``np.array(fill_value).dtype``.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    device : str, optional
        The device on which to place the created array. Default: None.
        For Array-API interoperability only, so must be ``"cpu"`` if passed.

        .. versionadded:: 2.0.0
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy array

In [ ]:
def custom_func():
  '''
  Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar or array_like
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, None, means
         ``np.array(fill_value).dtype``.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    device : str, optional
        The device on which to place the created array. Default: None.
        For Array-API interoperability only, so must be ``"cpu"`` if passed.

        .. versionadded:: 2.0.0
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.

        .. versionadded:: 1.20.0

    Returns
    -------
    out : ndarray
        Array of `fill_value` with the given shape, dtype, and order.

    See Also
    --------
    full_like : Return a new array with shape of input filled with value.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    zeros : Return a new array setting values to zero.

    Examples
    --------
    >>> np.full((2, 2), np.inf)
    array([[inf, inf],
           [inf, inf]])
    >>> np.full((2, 2), 10)
    array([[10, 10],
           [10, 10]])

    >>> np.full((2, 2), [1, 2])
    array([[1, 2],
           [1, 2]])
  '''

  pass

In [ ]:
custom_func

In [ ]:
np.full((3,3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
# 4 pixel image
photo_array = np.array([[230,36,16], [138,69,137], [45,89,189], [89,225,212]])
photo_array

array([[230,  36,  16],
       [138,  69, 137],
       [ 45,  89, 189],
       [ 89, 225, 212]])

+ 0 - dark, 255 - bright

In [ ]:
photo_array.shape

(4, 3)

In [ ]:
brightness_array = np.full(photo_array.shape, 10)
brightness_array

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [ ]:
photo_array + brightness_array

array([[240,  46,  26],
       [148,  79, 147],
       [ 55,  99, 199],
       [ 99, 235, 222]])

In [ ]:
photo_array - brightness_array

array([[220,  26,   6],
       [128,  59, 127],
       [ 35,  79, 179],
       [ 79, 215, 202]])

In [ ]:
#  fill more than 2 dimensions
np.full((2,4,3), 9)

array([[[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]]])

In [ ]:
#  lets try a differet datatype
np.full((2,3), 6.4)

array([[6.4, 6.4, 6.4],
       [6.4, 6.4, 6.4]])

In [ ]:
#  fill array with 6, but in float datatype
np.full((3,4), 6, float)

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [ ]:
#  fill array with 6, but in string datatype
np.full((3,4), 6, str)

array([['6', '6', '6', '6'],
       ['6', '6', '6', '6'],
       ['6', '6', '6', '6']], dtype='<U1')

In [ ]:
num = input('Enter a number: ')
num

Enter a number: 6


'6'

In [ ]:
num = input('Enter a number: ')
np.full((3,4), num, int)

Enter a number: 6


array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [ ]:
#  create array with zeros
np.full((5,3), 0)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.full((5,3), 0, str)

array([['0', '0', '0'],
       ['0', '0', '0'],
       ['0', '0', '0'],
       ['0', '0', '0'],
       ['0', '0', '0']], dtype='<U1')

`Using Zero Array Method`

In [ ]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((5,3), int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.zeros((5,3), str)

array([['', '', ''],
       ['', '', ''],
       ['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

`Using Arange Function`

In [ ]:
range(1,10)

range(1, 10)

+ 1
+ 1+1 = 2
+ 2+1 = 3
+ 3+1 = 4
....
+ 8+1 = 9

In [ ]:
for i in range(1,10,1):
  print(i)

1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(1,10,2):
  print(i)

1
3
5
7
9


Numpy has arange (its not arrange, with double r)
+ a - array
+ range

In [ ]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# create an array with values from 1 to 100
np.arange(1,101,1)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
np.arange(1,101,1).reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
np.arange(100,0,-1).reshape(20,5)

array([[100,  99,  98,  97,  96],
       [ 95,  94,  93,  92,  91],
       [ 90,  89,  88,  87,  86],
       [ 85,  84,  83,  82,  81],
       [ 80,  79,  78,  77,  76],
       [ 75,  74,  73,  72,  71],
       [ 70,  69,  68,  67,  66],
       [ 65,  64,  63,  62,  61],
       [ 60,  59,  58,  57,  56],
       [ 55,  54,  53,  52,  51],
       [ 50,  49,  48,  47,  46],
       [ 45,  44,  43,  42,  41],
       [ 40,  39,  38,  37,  36],
       [ 35,  34,  33,  32,  31],
       [ 30,  29,  28,  27,  26],
       [ 25,  24,  23,  22,  21],
       [ 20,  19,  18,  17,  16],
       [ 15,  14,  13,  12,  11],
       [ 10,   9,   8,   7,   6],
       [  5,   4,   3,   2,   1]])

`Using Random Method`

In [ ]:
# default random generates numbers between 0 to 1
np.random.random((3,4))

array([[0.78230436, 0.49323353, 0.94070664, 0.94155807],
       [0.29873338, 0.19826272, 0.17866828, 0.24581326],
       [0.97590428, 0.53948548, 0.09861421, 0.43517056]])

In [ ]:
# generate random numbers between 1 to 100
np.random.random((3,4)) * 100

array([[44.66568752, 36.13269235, 20.25231031, 46.77444477],
       [16.59406035,  7.09201281,  4.23117666, 19.49297906],
       [ 4.90770702,  4.4650341 , 85.03531979, 14.3872086 ]])

In [ ]:
#  randomly chosing numbers from list of choices
choices = [1,2,3,4,5,6]
np.random.choice(choices)

np.int64(6)

In [ ]:
np.random.choice(choices)

np.int64(5)

In [ ]:
np.random.choice(choices)

np.int64(1)

---------

**Mathematical Operations**

In [ ]:
#  python way
10 + 20

30

In [ ]:
#  Numpy way
np.sum([10, 20])

np.int64(30)

Element wise Addition

In [ ]:
maths =   [23,46,57,80]
science = [47,68,23,76]

In [ ]:
#  total score of student 1 using python way
s1_score = maths[0] + science[0]
s1_score

70

In [ ]:
scores = []

for score_1, score_2 in zip(maths, science):
  score = score_1 + score_2
  scores.append(score)

scores

[70, 114, 80, 156]

In [ ]:
#   sum of individual elements using numpy way
np.sum([maths, science])

np.int64(420)

In [ ]:
#  sum of individual student scores
np.sum([maths, science], axis=0)

array([ 70, 114,  80, 156])

In [ ]:
#  sum of individual subject scores
np.sum([maths, science], axis=1)

array([206, 214])

Subtraction

In [ ]:
np.subtract(20,5)

np.int64(15)

In [ ]:
np.multiply(10,20)

np.int64(200)

In [ ]:
# scalar multiplied with array
a = np.array([[1,2,3,4], [5,6,7,8]])

np.multiply(a, 5)

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40]])

In [ ]:
np.divide(20,5)

np.float64(4.0)

In [ ]:
np.remainder(10,3)

np.int64(1)

In [ ]:
np.sqrt(25)

np.float64(5.0)

In [ ]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712]])

In [ ]:
np.sin(1)

np.float64(0.8414709848078965)

In [ ]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029,  0.75390225, -0.14550003]])

In [ ]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154]])

**Statistical Operations**

In [ ]:
nums = [5,67,89,124,45,9,17,36]

In [ ]:
np.min(nums)

np.int64(5)

In [ ]:
np.max(nums)

np.int64(124)

In [ ]:
np.mean(nums)

np.float64(49.0)

In [ ]:
np.median(nums)

np.float64(40.5)

In [ ]:
np.std(nums)

np.float64(39.20140303611594)

In [ ]:
np.corrcoef(nums)

np.float64(1.0)

------------

**Array Comparisons**

In [ ]:
a = [1,2,4]
b = [2,4,4]
c = [1,2,4]

Element wise comparison

In [ ]:
np.equal(a, b)

array([False, False,  True])

In [ ]:
np.equal(a, c)

array([ True,  True,  True])

Array wise comparison

In [ ]:
np.array_equal(a,b)

False

In [ ]:
np.array_equal(a,c)

True

------------

**Slicing**

In [ ]:
nums = [5,67,89,124,45,9,17,36]

In [ ]:
nums[0]

5

In [ ]:
# first 3 elements
nums[0:3]

[5, 67, 89]

In [ ]:
nums[:]

[5, 67, 89, 124, 45, 9, 17, 36]

In [ ]:
nums = np.array(nums)
nums

array([  5,  67,  89, 124,  45,   9,  17,  36])

In [ ]:
nums[:3]

array([ 5, 67, 89])

In [ ]:
#  last 4 elements - using negative indexing
nums[-4:]

array([45,  9, 17, 36])

`2D Array Slicing`

In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

return [2,3], [5,6]

In [ ]:
#  step 1 - filter rows
a[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#  step 2 - filter cols
a[:2, 1:3]

array([[2, 3],
       [5, 6]])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

return [1,3], [4,6]

In [ ]:
a[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a[0:2, 0:3:2]

array([[1, 3],
       [4, 6]])