<a href="https://colab.research.google.com/github/srinivasan-06/Python_for_DataScience-/blob/main/Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
vector = np.arange(5)

In [ ]:
print(vector)

[0 1 2 3 4]


In [ ]:
matrix = np.arange(24).reshape(6,4)

In [ ]:
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
import pandas as pd
tips = pd.read_csv('tips.csv')

In [ ]:
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
tips.values # .values will convert a dataframe into a numpy array

array([[16.99, 1.01, 'Female', ..., 'Sun', 'Dinner', 2],
       [10.34, 1.66, 'Male', ..., 'Sun', 'Dinner', 3],
       [21.01, 3.5, 'Male', ..., 'Sun', 'Dinner', 3],
       ...,
       [22.67, 2.0, 'Male', ..., 'Sat', 'Dinner', 2],
       [17.82, 1.75, 'Male', ..., 'Sat', 'Dinner', 2],
       [18.78, 3.0, 'Female', ..., 'Thur', 'Dinner', 2]], dtype=object)

In [ ]:
mat1 = np.random.randint(10, 51, size = (3,3))
mat2 = np.random.randint(50, 100, size = (3,3))

In [ ]:
mat1

array([[50, 16, 14],
       [37, 40, 23],
       [12, 13, 22]])

In [ ]:
mat2

array([[60, 61, 89],
       [59, 76, 68],
       [77, 51, 61]])

In [ ]:
#addition of matrices
mat1 + mat2 #np.add(mat1, mat2)

array([[110,  77, 103],
       [ 96, 116,  91],
       [ 89,  64,  83]])

In [ ]:
mat1 + 10

array([[60, 26, 24],
       [47, 50, 33],
       [22, 23, 32]])

In [ ]:
#subtraction of matrices
mat1 - mat2

array([[-10, -45, -75],
       [-22, -36, -45],
       [-65, -38, -39]])

In [ ]:
#division of matrices
mat1 / 10

array([[5. , 1.6, 1.4],
       [3.7, 4. , 2.3],
       [1.2, 1.3, 2.2]])

In [ ]:
mat1 / mat2

array([[0.83333333, 0.26229508, 0.15730337],
       [0.62711864, 0.52631579, 0.33823529],
       [0.15584416, 0.25490196, 0.36065574]])

In [ ]:
#element-wise multiplication or Hadamard product
mat1 * mat2

array([[4048, 2040, 1780],
       [1104,  864, 3402],
       [1320, 2006, 2574]])

In [ ]:
#actual matrix multiplication : Dot product
mat1 @ mat2 #np.dot(mat1, mat2)

array([[8568, 5584, 9136],
       [6272, 4158, 6878],
       [6014, 4135, 6663]])

In [ ]:
mat1

array([[50, 16, 14],
       [37, 40, 23],
       [12, 13, 22]])

In [ ]:
#transpose of a matrix
mat1.T

array([[50, 37, 12],
       [16, 40, 13],
       [14, 23, 22]])

In [ ]:
#matrix rank : helps us to identify duplicate or redundant data
np.linalg.matrix_rank(mat1)

np.int64(3)

In [ ]:
#determinant of a matrix : whether a matrix is singular or not
np.linalg.det(mat1)

np.float64(20456.0)

In [ ]:
mat3 = np.arange(9).reshape(3,3)

In [ ]:
mat3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.linalg.det(mat3)

np.float64(0.0)

In [ ]:
#inverse of a matrix
np.linalg.inv(mat1)

array([[ 2.84024247e-02, -8.31052014e-03, -9.38599922e-03],
       [-2.63003520e-02,  4.55612045e-02, -3.08955808e-02],
       [ 4.88854126e-05, -2.23895190e-02,  6.88306609e-02]])

In [ ]:
np.linalg.inv(mat3)

LinAlgError: Singular matrix

In [ ]:
matrix = np.array([[3, -2],
                   [1, 0]])

In [ ]:
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Original Matrix: ")
print(matrix)
print('\nEigenvalues: ')
print(eigenvalues)
print('\nEigenvectors: ')
print(eigenvectors)

Original Matrix: 
[[ 3 -2]
 [ 1  0]]

Eigenvalues: 
[2. 1.]

Eigenvectors: 
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [ ]:
np.dot(matrix, [0.89442719, 0.4472136])

array([1.78885437, 0.89442719])

In [ ]:
np.array([0.89442719, 0.4472136]) * 2

array([1.78885438, 0.8944272 ])