<a href="https://colab.research.google.com/github/srinivasan-06/Python_for_DataScience-/blob/main/NumpyCaseStudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

** Create a function that takes dimensions as tuples e.g. (3, 3) and a numeric
value and returns a NumPy array of the given dimension filled with the
given value e.g.: solve((3, 3), 5) will return**

In [ ]:
def tup(dim, num):
  arr = np.full(dim,num)
  return arr

result = tup((3,3),5)
print(result)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


**Create a method that takes n NumPy arrays of the same dimensions,
sums them and returns the answer.**

In [ ]:
n = np.array([[1,2,3,4],[5,6,7,8]])


In [ ]:
def sum(n):
  return np.sum(n)
result = sum(n)
print(result)

36


** Given a 2 D Array of N X M Dimension, write a function that accepts this
array as well as two numbers N and M. The method should return the
top-left N X M sub matrix,**

In [ ]:
def sub_matrix(arr,N,M):
  return arr[:N,:M]